name: label-action
description: General-purpose action for issue labels

inputs:
  issue-number:
    description: The number of issue or pull request. Default to the current issue or pull request.
    required: false
  add-labels:
    description: List of labels to add (multiline)
    required: false
  remove-labels:
    description: List of labels to remove (multiline)
    required: false
  match-labels:
    description: List of patterns to match (multiline)
    required: false
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  added-labels:
    description: The labels added (multiline)
  added-count:
    description: The number of labels added
  added:
    description: If the labels were added, true. Otherwise, false.
  removed-labels:
    description: The labels removed (multiline)
  removed-count:
    description: The number of labels removed
  removed:
    description: If the labels were removed, true. Otherwise, false.
  matched-labels:
    description: The labels matched (multiline)
  matched-count:
    description: The number of labels matched
  matched:
    description: If the labels were matched, true. Otherwise, false.

runs:
  using: 'node20'
  main: 'dist/index.js'
